### ISSUE TITLE
epsilon.r.cpp - 还可以更美观

### ISSUE THREAD

**Issue by lightyears1998** [xiaokai666666/chaining-stage-by-xiaokai#16]
https://github.com/xiaokai666666/chaining-stage-by-xiaokai/blob/56b2c4df6eca9442b2fc87c1b855aee13282f148/eplison.cpp/eplison.r.cpp#L20-L31

变量winner的位置可以调整一下，使整体更美观

**Comment by GyuXiao** [comment]
谢谢~
