### ISSUE TITLE
alpha.e.cpp - 注释

### ISSUE THREAD

**Issue by lightyears1998** [xiaokai666666/chaining-stage-by-xiaokai#7]
https://github.com/xiaokai666666/chaining-stage-by-xiaokai/blob/06ab545da7fdaada1d833fa1c8959d07da4dc792/alpha.e.cpp#L13

此处应该是：

```cpp
// 加上char强制转换成char（字符类型），而不是“字符串”
```

**Comment by GyuXiao** [comment]
谢谢提醒
